Vagrant.configure("2") do |config|

  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = 'centos6.7'
  config.vm.network 'forwarded_port', guest: 3000, host: 3000

  config.vm.network 'private_network', ip: '192.168.33.15'

  config.vm.synced_folder '../', '/vagrant_data', type: 'nfs'
end