#!/bin/bash

red='\e[0;31m'
green='\e[0;m'
if [ ! -f ./dev_secret ]; then
    printf "${red}In order to run this application\ncreate file dev_secret with facebook APP_ID and APP_SECRET in your project root\n"
else
    source ./dev_secret
    rails s
fi

